version: '3'
services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./src/server:/home/src/server
      - ./src/client:/home/src/client
    depends_on:
      - postgres
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=genomedb
      - POSTGRES_PASSWORD=genomedb
      - POSTGRES_DB=genomedb
    ports:
      - "5432:5432"
    volumes:
      - ./src/server/seed:/docker-entrypoint-initdb.d/
      - genomepg:/var/lib/postgresql/data
volumes:
  genomepg:


