version: '3.6'
services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./src/server:/home/src/server
      - ./src/client:/home/src/client
    depends_on:
      - postgres
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=genomedb
      - POSTGRES_PASSWORD=genomedb
      - POSTGRES_DB=genomedb
    ports:
      - "5432:5432"
    volumes:
      - ./src/server/seed:/docker-entrypoint-initdb.d/
      - genomepg:/var/lib/postgresql/data
  mongo:
    image: mongo:4.2.3
    environment:
      - MONGO_INITDB_DATABASE=genomedb
    volumes:
      - ./src/server/seed/data:/seed/data
      - genomemongo:/data/db
    ports:
      - "27017:27017"
volumes:
  genomepg:
  genomemongo:
